# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

android.useAndroidX=true
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false

# Improved project import performance
android.dependency.useConstraints=false

org.gradle.jvmargs=-Xmx2048m
